### ISSUE TITLE
نسخه فعلی برنچ develop :warning:

### ISSUE THREAD

**Issue by niiima** [iran-react-community/docs#25]
<h2 lang="fa" dir="rtl" align="right">
:warning:پیش از هر تغییری 
  برنچ develop نیاز به به روز رسانی دارد 
</h2>

<div dir="rtl"><b>
برنچ develop-rescue   به این صورت ایجاد شده است تا با درختچه گیت مستر هماهنگ  باشد </b></div>

<pre dir="ltr">git checkout develop
git merge origin/master
//got many conflicts
git checkout . --theirs
</pre>

> برای جلوگیری از مشکلات آتی لطفا هر چه سریعتر بر روی نسخه فعلی برنچ دولوپ فورس پوش شود. 
> @amerllica 

<h2 lang="fa" dir="rtl" align="right">  نوع تغییرات </h2>

- [x] Bug fix (تغییرات شما را راهکار حل مشکلی در برنامه یا محتواست)
- [ ] New feature (موضوع یا قابلیت جدیدی را به مخزن اضافه میکنید)
- [x] Breaking change (تغییرات شما به حذف یا نیاز به تغییر قابلیت یا موضوع درحال کار پروژه منجر خواهد شد )
- [ ] این تغییرات نیاز به مستند سازی دارد

**Comment by amerllica** [comment]
@niiima 

<div dir=rtl>
سلام نیما جان، من یکم گیج شدم. چه اتفاقی افتاد؟ برچ دولوپ رو روی مستر فورس پوش کنم؟ دقیقا چرا؟ اون دولوپ-رسکیو چیه؟ یه کوچولو توضیح بدی متوجه می‌شم. در مورد فورس پوش آیا تو دسترسی نداری؟
</div>

**Comment by niiima** [comment]
<p dir=rtl>سلام @amer عزیز، به نظر میاد برنچ دولپ جدید به کسی دسترسی فورس پوش نمی ده حتی اگه ادمین باشه،بعد از فعال کردن ریویو های دو گانه، من سعی کردم با اجرای این دستور <code>git reset --hard develop master</code> به وضعیت فعلی و صحیح و بی خدشه ی مستر برگردم، موفق نشدم.</p>
<p dir=rtl>
حتی بعد از اینکه دسترسیم رو به پوش کننده تغییر دادم امکانش نبود.
متوجه شدم که #22  شروع تغییرات هست

**Comment by niiima** [comment]
<p dir=rtl>
#22  محلی هست که شما شروع به ساخت برنچ DEVELOP کردید و تا پیش از اون من به خاطر اینکه بتونیم یه قرارداد مناسب برای نامگذاری بین تیم داشته باشیم ، مثلا بتونیم ساب برنچهامون رو با پیشوند develop همراه کنیم
<pre dir=ltr> develop/project-name </pre> 
<p dir=rtl>و این قابلیت با داشتن یک برنچ فعال develop دیگه غیر ممکن هست، چون این ریفرنس وقتی وجود داشته باشه گیت اجازه نمیده ساب برنچی بر روی آخرین ریفرنست بسازی.
به جاش من از برنچ با نام dev از ابتدا پروژه رو بالا آوردم که پیشوند develop رو بین پروژه ها به اشتراک بتونیم استفاده کنیم که بهمون دسترسی به دستوراتی برای بچ کردن فرایند های اپتیمایز مثل حذف زیربرنجها به صورت همزمان با اجرای کامند زیر برای حذف پروژه های در حال دولوپ یکی از نهادها یا حوزه های فعالیت بهمون میده. البته بسیاری از این مسایل با برنچهای  feature/ هم مقدور هست، با این حال برنچینگ هر چه ساده تر موثرتر
<pre dir=ltr> λ git branch | grep 'develop/deprecated-project-title | xargs git branch -D</pre>

<h3 dir=rtl>دستورات مقتضی به اجرا:</h3>
<pre dir=ltr> 
λ git log --stat // بتونیم منظری از تغییرات رو تا این کامیت دنبال کنیم
λ git reflog // یک نگاهی هم به ریفرنسها بندازیم
λ git checkout master
λ git reset --hard xxxxxx
λ git push --force
</pre>
<p dir=rtl>
نظرت چیه که تا پیش از ریست رو باهم سینک شیم @amerllica و به جای برنچ develop از همون dev که تا اونجا داشت کارش رو انجام میداد برگردونیم. در ادامه از نامهای چون <code>iran-react-comunity/docs/develop/iran-react-community.github.io<code>
 استفاده کنیم

**Comment by niiima** [comment]
> @niiima
> 
> سلام نیما جان، من یکم گیج شدم. چه اتفاقی افتاد؟ برچ دولوپ رو روی مستر فورس پوش کنم؟ دقیقا چرا؟ اون دولوپ-رسکیو چیه؟ یه کوچولو توضیح بدی متوجه می‌شم. در مورد فورس پوش آیا تو دسترسی نداری؟

<p  dir=rtl> عامر جان من دسترسی ندارم، از طریق رابطه @iran-react-community/docs-and-conventions
با کامیونیتی دسترسیم به پوش مستقیم باز هست، اما برای مدیریت متمرکز و حل مشکلات احتمالی ازت جویا میشم، بهم دسترسی بدون نیاز به دو ریویو رو بدی تا بتونم مستقیما روند گیت رو همراهی  کنم به عنوان نگهدارنده روی گیت فعالیت کنم.  چون با محدودیت هایی که بر برنچ جدید گذاشتی، این امکان رو شاید به خودت هم نداده باشی. و اصولا یک پالایش نهایی باید توسط محدود ترین تعداد افراد ممکن اعمال بشه، هماهنگی نزدیکی لازمه وجود داشته باشه،  که چنین مشکلاتی رخ نده، البته گیت هست و این مشکلات، مهم این هست الان وضعیت ریپوی خودت رو هم به منبع انتقال بدی بخشی از مشکلات حل میشه،
ولی برای راه خل کلی مطالبی را به اختصار در بدنه #25  عنوان کردم.
</p>
<i dir=rtl>
صورت مسئله حکایت از این داره که هر دو پروژه رو تغییر دادیم، بخشی که از روی گیت هاب اعمال شده مثل 
 محدودیت ها، پیغام های یا هش ایندکس های ریپوی ریموت رو تغییر میده و بدون سینک هم به روز نمیشه روی لوکال، این شده که پس از تغییرات شما من متوجه این تغییر نام شدم، پروژه رو فچ کردم، حتی به برنچ تازه develop هم سلام گفتم، چون تازه به وجود اومده بود توسط شما و تا اون موقع برنچ dev مسئولیت اون رو به عهده داشت. با این حال در ادامه به روال قبل از ایجاد محدودیت 2 ریوو روی برنچ ها کار میکردم که شامل ایجاد تغییرات بر روی dev و خروجی نهایی بر روی master پس از هر چند مورد بود و مطالبی را در بر میگرفت مثل تمپلیت پول ریکوئست و موارد خرد دیگر که با توجه به ماهیتشان تا این زمان هم میتونست به تعویق نیفته و مراحل تست رو بگذرونه.</p>
</i>
<ul dir=rtl>
<li>با کامند های عنوان شده و تخصص خودتون به همراه عکسهایی که از مخزن و سابقه گرافیش ارسال کردم، کنار این اطلاعات به راه مشترک برسیم و اِعمال کنیم.

<li>ضمنا برای نگهداری فعالیت های اشخاص به نام خودشان لطفا مستقیما برای مستر پول ریکوئست ها داده شود #22 
</ul>

**Comment by amerllica** [comment]
@niiima 

<div dir=rtl>
نیما جان خیلی پیچیده شد. احساس می‌کنم به یک تماس اسکایپی یا حتی دیدار حضوری نیاز داریم. ولی چی شد که این ریپو به این سادگی با چندتا فایل و دوتا برنچ به این مشکل خورد؟ آیا تعویض نام من از dev به develop موارد رو بهم ریخته کرد؟
<br>
<br>
اگر آره که خوب اشکالی نداره. تو همین الآن هم جزو نگهدارندگان هستی،‌من رفتم توی تنظیمات و همونطوری که تو dev و master پروتکت کرده بودی من هم develop رو پروتکت کردم. فکر می‌کنم با دسترسی‌ای تو داری می‌تونی موقتا پروتکت رو برداری و پوش‌ها و فورس پوش‌ها رو انجام بدی و بعدش دوباره تنظیمات رو برگردونی.
<br>
<br>
اگر اینطوری نیست که بفرما من سریعا پروتکت‌ها رو بردارم. شما انقدر در موارد گیت حرفه‌ای هستید که احساس می‌کنم توی این موارد باید تمامی دسترسی‌ها رو داشته باشید. هر نوع دسترسی‌ای خواستید بفرمایید که به شما بدم. شما از یاران اولیه این جامعه بودید و هستید و خواهید بود.
</div>

**Comment by niiima** [comment]
<p dir=rtl>ارادت و تشکر عامر عزیز، ممنونم از اعتماد و لطفی که به من داشتید و داربد، بله دسترسی برداشتنش رو داشتم، اما برای همین که با هم سینک باشیم بازش نکرده بودم، بعد از اندکی مطالعه بیشتر ساختار رو به صورت سینک تری پیش میبریم.
در رابطه با قسمت ابتدای سوالت سعی کردم توضیحاتی رو برات بدم، که جمعا از این قرار بود که من با سطح دسترسیم روی مستر مستقیما پوش کردم که اون تغییرات توی مرج نشدند، چون توی اون برنچ دسترسیم دو ریوو بوده، برای جلوگیری از پیش آمد های آتی خواستم اطلاع بدم و این رویه رو اصلاح کنیم که با غیر همسان بودن برنچهای اصلیمون برخورد نکنیم.

**Comment by niiima** [comment]
@amerllica  توی[ این کامنت](https://gist.github.com/santisbon/a1a60db1fb8eecd1beeacd986ae5d3ca#gistcomment-2932525) که مال همین چند روز پیش هست به این نکته اشاره داره اگر مرج کننده نهایی یک نفر نباشه جالب نیست، و اینکه چطور ساده میشن حل مشکلات احتمالی در صورنی که مرج به صورت متمرکر انجام شه و سابقه تغییرات دو نفر که حتما با هم یکی نیست در جاهایی 
درخت گیت رو مخدوش نکنه.

**Comment by niiima** [comment]
<p dir=rtl>پس از یکسان سازی برنچها  ساختار به شکل پیشین خود در آمد و دسترسی ها به صورت پیش فرض بازگردانده شد.
لطفا برای دریافت کامل و به روز رسانی مخازن خود از <code >git fetch -p origin</code > استفاده نمایید </p>
