### ISSUE TITLE
ایراد نگارشی در مرام‌نامه

### ISSUE THREAD

**Issue by aliwesome** [iran-react-community/docs#6]
<p dir=rtl>
در جمله‌ی دوم از پاراگراف اول یه ایراد نگارشی دیده میشه که جمله رو بی‌معنی کرده.
</p>

**Comment by niiima** [comment]
<div dir="rtl">لطفا جمله مورد نظر رو کوت کنید تا با هم اصلاح کنیم.</div>

**Comment by nimahkh** [comment]
> در جمله‌ی دوم از پاراگراف اول یه ایراد نگارشی دیده میشه که جمله رو بی‌معنی کرده.

<p dir=rtl>
<div dir=rtl>
در لینک زیر تغییراتی انجام شده است 
</div>

<div dir=rtl>
<a  href="https://github.com/iran-react-community/docs/issues/8">
تغییرات در مرام نامه
</a>
</div>
</p>

**Comment by amerllica** [comment]
<p dir=rtl>
مرسی از دوستان بابت پیگیری. اصلاحات توسط نیما حبیب‌خدا به صورت PR ارسال شد. در یک issue متفاوت درحال بررسی هست. من با اجازه دوستان این issue رو می‌بندم
</p>
