### ISSUE TITLE
استفاده از نگارش درست فارسی

### ISSUE THREAD

**Issue by mehrdad88sh** [iran-react-community/docs#9]
<p dir=rtl>
پیشنهاد میشه برای بعضی از عبارات از کلمات بهتری استفاده شود.
<br/>
<br/>
برای مثال قسمتی را تغییر دادم.
</p>

**Comment by niiima** [comment]
@mehrdad88sh 

<div dir="rtl">
 ضمن تشکر از توجه و پیشنهاد تغییر صحیح شما اجازه میخوام خواهش کنم درخواست تجمیع جدیدی با 
   اعمال تغییرات مورد نظرتان بر روی برنچ جدید dev .برای ما ارسال نمایید تا روند تجمیع ابتدا بر روی این برنج و سپس بر روی مستر نهاده شود
 </div>

[PR](https://github.com/iran-react-community/docs/pull/10#pullrequestreview-246807376)

**Comment by amerllica** [comment]
@niiima 

<div dir=rtl>
مرسی از شما نیمای عزیزم که انقدر با مسئولیت کارها رو پیگیری می‌کنید. متاسفانه بستر گیت‌هاب برای فارسی نویسی آماده نیست. اگر می‌خواهید که کسی رو منشن کنید بیرون از مارک‌اپ و با یک خط فاصله این کار رو انجام بدید. یا اگر می‌خواهید که مارک‌دان بنویسید باید از پایین هم یک خط فاصله بدید تا مفصر بفهمه. حتی برای لینک دادن متاسفانه باید از مارکاپ a استفاده کرد وگرنه شاهد بهم ریختی بدی خواهید بود. از همه الطاف شما سپاسگذارم.
</div>
